### ISSUE TITLE
memcached.so does not exist

### ISSUE THREAD

**Issue by Nemo64** [Chialab/docker-php#8] opened 2017-05-03 08:27 UTC
I am currently trying to install opcache in the php containers (see: #7), however all old images are failing while building because of memcached. I'm trying to figure out why.

I run the test like with this little script

```bash
#!/usr/bin/env bash
set -e

for version in 5.4 5.5 5.6 7.0 7.1
do
    make build-nopull VERSION=${version}
    make test VERSION=${version}
done

for version in 5.4 5.5 5.6 7.0 7.1
do
    make build-nopull -C dev/ VERSION=${version}
    make test -C dev/ VERSION=${version}
done

```

**Comment by fquffio** [comment] 2017-05-03 09:03
First of all, thanks again for your interest. :)

Problem seems to be that PECL Memcached now requires PHP ≥ 7.0 (see also [here](https://hub.docker.com/r/chialab/php/builds/bhkiztafwxzbpwqxybsteev/)):
```
Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20100525/

Installing header files:          /usr/local/include/php/

[91mdocker-php-ext-enable gd.so 
[0m
find . -name \*.gcno -o -name \*.gcda | xargs rm -f

find . -name \*.lo -o -name \*.o | xargs rm -f

find . -name \*.la -o -name \*.a | xargs rm -f 

find . -name \*.so | xargs rm -f

find . -name .libs -a -type d|xargs rm -rf

find . -name \*.1 | xargs rm -f

rm -f libphp.la   modules/* libs/*

pecl/memcached requires PHP (version >= 7.0.0), installed version is 5.4.45

pecl/memcached can optionally use PHP extension "igbinary" (version >= 2.0)

pecl/memcached can optionally use PHP extension "msgpack" (version >= 2.0)
```

A possible fix could be https://github.com/docker-library/php/issues/132#issuecomment-280971189.

As a side note, I noticed that Travis build, which is supposed to run once a week, was skipped for more than three months due to the last commit including `[ci skip]`, otherwise we could have noticed this problem earlier.

**Comment by fquffio** [comment] 2017-05-03 09:28
@Nemo64 There is some chance that the problem is now fixed. I have opened a PR (#9). Do you have time to take a quick look at that before being merged?

**Closed** 2017-05-03 12:38 UTC
Labels: bug
