### ISSUE TITLE
"Cannot load Xdebug - it was already loaded"

### ISSUE THREAD

**Issue by DavidCarrington** [chialab/docker-php#64] opened 2020-01-20 14:43 UTC
I've only tested against chialab/php-dev:7.4

`php --ini` reports two different files trying to load xdebug, xdebug.ini and docker-php-ext-xdebug.ini, so these error is appearing in various output.

Can one of these references be removed? It looks like xdebug.ini is created by the Dockerfile within this project.

**Comment by le0m** [comment] 2020-01-20 15:35
Hello and thanks for reporting the issue.

This is caused by #61 on versions 5.6+, I'll fix it asap.

**Comment by le0m** [comment] 2020-01-20 16:14
Referenced commit fixes the issue, I'm closing this.

**Closed by le0m** 2020-01-20 16:14 UTC
